# Generated by Django 3.2.6 on 2023-07-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfileupload',
            name='summary',
            field=models.CharField(max_length=5000000, null=True),
        ),
    ]
