# Generated by Django 3.2.6 on 2023-07-28 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0002_myfileupload_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfileupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
